name: Docker Test
on: [push, pull_request]

jobs:
  docker-test:
    name: Docker
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: nodegoat:{{ github.ref }}