name: Docker Test
on: [push, pull_request]

jobs:
  docker-test:
    name: Docker
    runs-on: ubuntu-latest
    env:
      LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
      LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get short SHA
        run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: nodegoat:${{ env.GHA_SHA }}

      - name: Docker images
        shell: docker images ls

      - name: Lacework vulnerability scan
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install curl
          curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
          chmod +x lw-scanner
          ./lw-scanner evaluate nodegoat ${{ env.GHA_SHA }} --build-id ${{ github.run_id }}
