name: Docker Test
on: [push, pull_request]

jobs:
  docker-test:
    name: Docker
    runs-on: ubuntu-latest
    env:
      LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
      LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get short SHA
        run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: nodegoat:${{ env.GHA_SHA }}
          load: true

      - name: lw-scanner
        uses: timarenz/lw-scanner-action@v0.2.0
        with:
          image_name: nodegoat
          image_tag: ${{ env.GHA_SHA }}
          fail_only_if_vulnerabilities_fixable: true
          scan_library_packages: true
